<?php
    /** @var PageViewModel $pageViewModel */

use src\interfaces\PageViewModel;

?>
<!DOCTYPE html>
<html>
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style type="text/css">
            body, html {
                padding: 0;
                margin: 0;
                width: 100%;
                min-height: 100%;
                font-family: Verdana, sans-serif;
                color: #333;
                box-sizing: border-box;
            }

            .page-header {
                width: 100%;
                height: 60px;
                background-color: #005ea8;
                margin-bottom: 15px;
                font-size: 25px;
                font-weight: bold;
                color: white;
                line-height: 60px;
                padding: 0 15px 0 15px;
            }

            .teaser {
                height: 220px;
                border-bottom: 1px solid #ccc;
                margin-bottom: 15px;
                display: flex;
                justify-content: center;
            }

            .footer {
                height: 60px;
                border-top: 1px solid #ccc;
                margin-top: 30px;
                display: flex;
                justify-content: center;
                padding-top: 30px;
            }

            .container {
                width: 1280px;
            }
        </style>
    </head>
    <body>
        <header class="page-header">
            CHECK24
        </header>
        <div class="teaser">
            <div class="container">
                <h2>Festgeld Vergleich: Top Festgeldzinsen sichern</h2>
                <h4>Tages- und Festgeldkonten aller wichtigen Anbieter im Vergleich</h4>
            </div>
        </div>
        <?= $pageViewModel->getReactHTML() ?>
    <footer class="footer">
        Footer
    </footer>
    </body>
</html>

